name: emoji_selector
homepage: https://github.com/Alfaizkhan/flutter-emoji-selector
issue_tracker: https://github.com/Alfaizkhan/flutter-emoji-selector/issues
description: An Emoji picker component for Flutter with the latest set of emojis. The current version supports Emoji version 15.
repository: https://github.com/Alfaizkhan/flutter-emoji_selector
version: 0.0.6

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  design_system:
    git:
      url: https://github.com/definev/genit.git
      path: core/design_system
      ref: main
  
  mix: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/emoji_selector/data/emoji.json
